### ISSUE TITLE
Cumulative Round Time

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#12]
I was trying to determine cumulative execution time of a Baloo Round with `n` scheduled slots.

I was wondering if there was a way within GMW to determine this already.

I personally tried the following code, though it does not seem quite right (final slots are consistently skipped):
```
#define TOTAL_T_ROUND_COMPUTE(n)    (((GMW_CONF_T_DATA + GMW_CONF_T_GAP)*(n) + GMW_CONF_T_CONTROL + GMW_CONF_T_GAP_CONTROL) / 1000LU) // in ms
```

So I was wondeing what other parameters I should take into account.

**Comment by romain-jacob** [comment]
The executed total time of a round is tracked by the middleware and stored in the `measured_round_time_ms` local variable (from sending of the control packet till the very end of the round - just before yielding). If you are interested in this variable, you can add it to the `stats` structure and access it at the NET layer via the `gmw_get_stats()` function.

Regarding your formula, it looks right a priori. I am not sure exactly what you are interesting in measuring though. Maybe you are off because of the pre-process?

**Comment by swarth100** [comment]
Ooh!
Thank you! `stats` looks super useful to easily expose information from GMW!

So mainly I am interested in timing how long it takes from when the Control packet is sent to when the `on_round_finished()` callback terminates. If I am able to estimate this time as accurately as possible I was aiming to have back-to-back floods with minimal delay.

If we define:
```
#define GMW_CONF_MAX_SLOTS    26
#define T_ROUND               TOTAL_T_ROUND_COMPUTE(GMW_CONF_MAX_SLOTS)
#define T_PERIOD              2000
```

This way if I were to perform 2 back-to-back rounds I was thinking of doing the following:

```
#--------------#-----------------#------------------#------------------#
| ROUND number | schedule.period | schedule.n_slots | PRE/POST process |
#--------------#-----------------#------------------#------------------#
|       1      |     T_ROUND     |        26        |       NULL       |
#--------------#-----------------#------------------#------------------#
|       2      |     T_ROUND     |        26        |       NULL       |
#--------------#-----------------#------------------#------------------#
|       3      |     T_PERIOD    |         0        |     &process     |
#--------------#-----------------#------------------#------------------#
```

The first two rounds actually hold the communication info to query all the nodes. The final round is just to notify the whole network that everyone can now call the pre/post processes and wait for a much longer time. During the back-to-bakc calls PRE/POST are set to `NULL`.

**Comment by romain-jacob** [comment]
The problem is that there are some small delays between two rounds that you don't account for. Look for the `GMW_CONF_PREROUND_SETUP_TIME` macro. 

I think adding this to your macro should do the trick. Another approach is to monitor online the length of the round, instead of trying to predict it. This may or may not be useful in your case, but you could do that

**Comment by swarth100** [comment]
Thank you so much!
