### ISSUE TITLE
Modify Schedule n_slots dynamically

### ISSUE THREAD

**Issue by swarth100** [ETHZ-TEC/Baloo#8]
I was wondering if there was a current effort to support dynamic changes to the `n_slots` parameter of the schedule, to allow to have varying schedules with different nodes at different time intervals.

A little background on how I would use this feature:

I am trying to reimplement the contents of the following paper within Baloo:
 Beshr Al Nahas, Simon Duquennoy and Olaf Landsiedel. 2017. "Network-wide Consensus Utilizing the Capture Effect in Low-power Wireless Networks". In Proceedings of the Conference on Embedded Networked Sensor Systems (ACM SenSys)

This means starting from 2PC and 3PC and then building my way to more robust consensus protocols.

When working from 2PC I need a way to tell each source node wether their vote (cast in the previous round) has been registered or not by the host. In the paper they achieve this through packet aggregation on each node, though from my understanding this does not fit well with Baloo's design: each node transmits at each round (if scheduled), so rather than having big packets we constantly aggregate into, it is best to have small and slim packets to reduce the overall time taken to perform each round.

Therefore my current issue: the host asks all source nodes to cast their vote. All nodes vote in the next round, but lets assume that one vote is lost. Currently I see three ways of fixing this:

1. **I ask all nodes again to vote**. Nodes are unaware if their vote was registered, but voting is deterministic hence they will vote in the same exact way again when prompted to vote again by the host. The host keeps track of the votes received the previous round and aggregates all the missing votes at the next round. Drawback: with *n* nodes we have *n* messages at each round even if we only are missing 1 vote.
2. I have a **slightly larger packet** that **tells the source nodes which votes have been received**. This means that upon inspecting the message broadcast by the host, source nodes which know their vote has been received will not vote again. Benefit: fewer messages in the network. Drawback: same completion time as part 1 (as all nodes will have to be scheduled anyways), additionally the host is now sending a bigger packet around the network.
3. **Alter the schedule for the next round**. If I could alter the schedule for the next round to just schedule all nodes from which I have been unable to register a reply, to vote again, this would not increase the size of the host packets, and overall greatly reduce the time to complete as all nodes from which I already have votes will not have a scheduled slot within which they stay quiet.

So overall I was wondering if the "Modify schedule.n_slots" currently listed within WIP will be worked on soon, so I can design around poits 1, 2 or 3 accordingly. Or is there a feature of Baloo which already does solve this issue?

**Comment by romain-jacob** [comment]
If I understand what you are asking, you want to change the number and/or assignments of slots between rounds: is that correct? If so, this comes out-of-the-box in Baloo. This control information is part of the [schedule section of the control packet](https://github.com/ETHZ-TEC/Baloo/wiki/Baloo-control-packet#1-the-schedule-section).

The program flow would be: Start 2PC in one round by collecting votes. At the end of the round, the host assess which votes were received and prepare the new schedule, which would contain only the X slots required (where X is the number of missing votes), and the corresponding assignment in the [`slot` array](https://github.com/ETHZ-TEC/Baloo/wiki/Baloo-control-packet#slot-array). What __cannot be changed__ at runtime is the maximal number of slots in one round (set by `#define GMW_CONF_MAX_SLOTS` with a default of 10).

An alternative would be to [use Chaos](https://github.com/ETHZ-TEC/Baloo/wiki/primitive-chaos) (instead of Glossy) to collect the votes. That would most likely be more efficient, but it is also a bit more complex to setup.

The "Modify schedule.n_slots"  feature from the WiP list will not change any of this. Simply, at the moment setting control.schedule.n_slots = X overwrites the [control flags](https://github.com/ETHZ-TEC/Baloo/wiki/Baloo-control-packet#n_slots). This is very easy to solve, but will wait until a new release.

**Comment by swarth100** [comment]
Thank you so much for your reply!

I'm really sorry I completely missed we have complete control over the control packet updating it on every round-finish.

Working on it with your new guidance!

Out of interest, what would be the procedure/guidelines for upstream pushes to Baloo?
Is the project open to contributions for additional algorithms? If so is it preferred to submit a preliminary PR and then solve all problems from there, or are there strong requirements that need to be fullfilled prior to submitting the PR?

The idea is to always test everything on FLocklab prior to contributing, was just wondering if any further steps

(I think usually all would be covered from within "Contributing" and "Pull request template" sections of the [community profile](https://help.github.com/en/articles/about-community-profiles-for-public-repositories))

**Comment by romain-jacob** [comment]
> I'm really sorry I completely missed we have complete control over the control packet updating it on every round-finish.

No problem.

> Out of interest, what would be the procedure/guidelines for upstream pushes to Baloo?

As you said, the standard pull request procedure applies. I did not think as far as hard "requirements", I guess this would depend on the nature of the contribution.
